using System;
using System.Threading;

namespace CyberChatbot
{
    // This class handles the visual appearance of the chatbot
    public class UIHelper
    {
        // Method to display ASCII logo
        public static void ShowLogo()
        {
            Console.ForegroundColor = ConsoleColor.Cyan;

            // Multiline ASCII string
            string ascii = @"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
        CCCCCCCCCCCCCYYYYYYY       YYYYYYYBBBBBBBBBBBBBBBBB   EEEEEEEEEEEEEEEEEEEEEERRRRRRRRRRRRRRRRR      SSSSSSSSSSSSSSS EEEEEEEEEEEEEEEEEEEEEE       CCCCCCCCCCCCCUUUUUUUU     UUUUUUUURRRRRRRRRRRRRRRRR   IIIIIIIIIITTTTTTTTTTTTTTTTTTTTTTTYYYYYYY       YYYYYYY                    AAA   WWWWWWWW                           WWWWWWWW   AAA               RRRRRRRRRRRRRRRRR   EEEEEEEEEEEEEEEEEEEEEENNNNNNNN        NNNNNNNNEEEEEEEEEEEEEEEEEEEEEE   SSSSSSSSSSSSSSS    SSSSSSSSSSSSSSS      BBBBBBBBBBBBBBBBB        OOOOOOOOO     TTTTTTTTTTTTTTTTTTTTTTT
     CCC::::::::::::CY:::::Y       Y:::::YB::::::::::::::::B  E::::::::::::::::::::ER::::::::::::::::R   SS:::::::::::::::SE::::::::::::::::::::E    CCC::::::::::::CU::::::U     U::::::UR::::::::::::::::R  I::::::::IT:::::::::::::::::::::TY:::::Y       Y:::::Y                   A:::A  W::::::W                           W::::::W  A:::A              R::::::::::::::::R  E::::::::::::::::::::EN:::::::N       N::::::NE::::::::::::::::::::E SS:::::::::::::::S SS:::::::::::::::S     B::::::::::::::::B     OO:::::::::OO   T:::::::::::::::::::::T
   CC:::::::::::::::CY:::::Y       Y:::::YB::::::BBBBBB:::::B E::::::::::::::::::::ER::::::RRRRRR:::::R S:::::SSSSSS::::::SE::::::::::::::::::::E  CC:::::::::::::::CU::::::U     U::::::UR::::::RRRRRR:::::R I::::::::IT:::::::::::::::::::::TY:::::Y       Y:::::Y                  A:::::A W::::::W                           W::::::W A:::::A             R::::::RRRRRR:::::R E::::::::::::::::::::EN::::::::N      N::::::NE::::::::::::::::::::ES:::::SSSSSS::::::SS:::::SSSSSS::::::S     B::::::BBBBBB:::::B  OO:::::::::::::OO T:::::::::::::::::::::T
  C:::::CCCCCCCC::::CY::::::Y     Y::::::YBB:::::B     B:::::BEE::::::EEEEEEEEE::::ERR:::::R     R:::::RS:::::S     SSSSSSSEE::::::EEEEEEEEE::::E C:::::CCCCCCCC::::CUU:::::U     U:::::UURR:::::R     R:::::RII::::::IIT:::::TT:::::::TT:::::TY::::::Y     Y::::::Y                 A:::::::AW::::::W                           W::::::WA:::::::A            RR:::::R     R:::::REE::::::EEEEEEEEE::::EN:::::::::N     N::::::NEE::::::EEEEEEEEE::::ES:::::S     SSSSSSSS:::::S     SSSSSSS     BB:::::B     B:::::BO:::::::OOO:::::::OT:::::TT:::::::TT:::::T
 C:::::C       CCCCCCYYY:::::Y   Y:::::YYY  B::::B     B:::::B  E:::::E       EEEEEE  R::::R     R:::::RS:::::S              E:::::E       EEEEEEC:::::C       CCCCCC U:::::U     U:::::U   R::::R     R:::::R  I::::I  TTTTTT  T:::::T  TTTTTTYYY:::::Y   Y:::::YYY                A:::::::::AW:::::W           WWWWW           W:::::WA:::::::::A             R::::R     R:::::R  E:::::E       EEEEEEN::::::::::N    N::::::N  E:::::E       EEEEEES:::::S            S:::::S                   B::::B     B:::::BO::::::O   O::::::OTTTTTT  T:::::T  TTTTTT
C:::::C                 Y:::::Y Y:::::Y     B::::B     B:::::B  E:::::E               R::::R     R:::::RS:::::S              E:::::E            C:::::C               U:::::D     D:::::U   R::::R     R:::::R  I::::I          T:::::T           Y:::::Y Y:::::Y                  A:::::A:::::AW:::::W         W:::::W         W:::::WA:::::A:::::A            R::::R     R:::::R  E:::::E             N:::::::::::N   N::::::N  E:::::E             S:::::S            S:::::S                   B::::B     B:::::BO:::::O     O:::::O        T:::::T        
C:::::C                  Y:::::Y:::::Y      B::::BBBBBB:::::B   E::::::EEEEEEEEEE     R::::RRRRRR:::::R  S::::SSSS           E::::::EEEEEEEEEE  C:::::C               U:::::D     D:::::U   R::::RRRRRR:::::R   I::::I          T:::::T            Y:::::Y:::::Y                  A:::::A A:::::AW:::::W       W:::::::W       W:::::WA:::::A A:::::A           R::::RRRRRR:::::R   E::::::EEEEEEEEEE   N:::::::N::::N  N::::::N  E::::::EEEEEEEEEE    S::::SSSS          S::::SSSS                B::::BBBBBB:::::B O:::::O     O:::::O        T:::::T        
C:::::C                   Y:::::::::Y       B:::::::::::::BB    E:::::::::::::::E     R:::::::::::::RR    SS::::::SSSSS      E:::::::::::::::E  C:::::C               U:::::D     D:::::U   R:::::::::::::RR    I::::I          T:::::T             Y:::::::::Y                  A:::::A   A:::::AW:::::W     W:::::::::W     W:::::WA:::::A   A:::::A          R:::::::::::::RR    E:::::::::::::::E   N::::::N N::::N N::::::N  E:::::::::::::::E     SS::::::SSSSS      SS::::::SSSSS           B:::::::::::::BB  O:::::O     O:::::O        T:::::T        
C:::::C                    Y:::::::Y        B::::BBBBBB:::::B   E:::::::::::::::E     R::::RRRRRR:::::R     SSS::::::::SS    E:::::::::::::::E  C:::::C               U:::::D     D:::::U   R::::RRRRRR:::::R   I::::I          T:::::T              Y:::::::Y                  A:::::A     A:::::AW:::::W   W:::::W:::::W   W:::::WA:::::A     A:::::A         R::::RRRRRR:::::R   E:::::::::::::::E   N::::::N  N::::N:::::::N  E:::::::::::::::E       SSS::::::::SS      SSS::::::::SS         B::::BBBBBB:::::B O:::::O     O:::::O        T:::::T        
C:::::C                     Y:::::Y         B::::B     B:::::B  E::::::EEEEEEEEEE     R::::R     R:::::R       SSSSSS::::S   E::::::EEEEEEEEEE  C:::::C               U:::::D     D:::::U   R::::R     R:::::R  I::::I          T:::::T               Y:::::Y                  A:::::AAAAAAAAA:::::AW:::::W W:::::W W:::::W W:::::WA:::::AAAAAAAAA:::::A        R::::R     R:::::R  E::::::EEEEEEEEEE   N::::::N   N:::::::::::N  E::::::EEEEEEEEEE          SSSSSS::::S        SSSSSS::::S        B::::B     B:::::BO:::::O     O:::::O        T:::::T        
C:::::C                     Y:::::Y         B::::B     B:::::B  E:::::E               R::::R     R:::::R            S:::::S  E:::::E            C:::::C               U:::::D     D:::::U   R::::R     R:::::R  I::::I          T:::::T               Y:::::Y                 A:::::::::::::::::::::AW:::::W:::::W   W:::::W:::::WA:::::::::::::::::::::A       R::::R     R:::::R  E:::::E             N::::::N    N::::::::::N  E:::::E                         S:::::S            S:::::S       B::::B     B:::::BO:::::O     O:::::O        T:::::T        
 C:::::C       CCCCCC       Y:::::Y         B::::B     B:::::B  E:::::E       EEEEEE  R::::R     R:::::R            S:::::S  E:::::E       EEEEEEC:::::C       CCCCCC U::::::U   U::::::U   R::::R     R:::::R  I::::I          T:::::T               Y:::::Y                A:::::AAAAAAAAAAAAA:::::AW:::::::::W     W:::::::::WA:::::AAAAAAAAAAAAA:::::A      R::::R     R:::::R  E:::::E       EEEEEEN::::::N     N:::::::::N  E:::::E       EEEEEE            S:::::S            S:::::S       B::::B     B:::::BO::::::O   O::::::O        T:::::T        
  C:::::CCCCCCCC::::C       Y:::::Y       BB:::::BBBBBB::::::BEE::::::EEEEEEEE:::::ERR:::::R     R:::::RSSSSSSS     S:::::SEE::::::EEEEEEEE:::::E C:::::CCCCCCCC::::C U:::::::UUU:::::::U RR:::::R     R:::::RII::::::II      TT:::::::TT             Y:::::Y               A:::::A             A:::::AW:::::::W       W:::::::WA:::::A             A:::::A   RR:::::R     R:::::REE::::::EEEEEEEE:::::EN::::::N      N::::::::NEE::::::EEEEEEEE:::::ESSSSSSS     S:::::SSSSSSSS     S:::::S     BB:::::BBBBBB::::::BO:::::::OOO:::::::O      TT:::::::TT      
   CC:::::::::::::::C    YYYY:::::YYYY    B:::::::::::::::::B E::::::::::::::::::::ER::::::R     R:::::RS::::::SSSSSS:::::SE::::::::::::::::::::E  CC:::::::::::::::C  UU:::::::::::::UU  R::::::R     R:::::RI::::::::I      T:::::::::T          YYYY:::::YYYY           A:::::A               A:::::AW:::::W         W:::::WA:::::A               A:::::A  R::::::R     R:::::RE::::::::::::::::::::EN::::::N       N:::::::NE::::::::::::::::::::ES::::::SSSSSS:::::SS::::::SSSSSS:::::S     B:::::::::::::::::B  OO:::::::::::::OO       T:::::::::T      
     CCC::::::::::::C    Y:::::::::::Y    B::::::::::::::::B  E::::::::::::::::::::ER::::::R     R:::::RS:::::::::::::::SS E::::::::::::::::::::E    CCC::::::::::::C    UU:::::::::UU    R::::::R     R:::::RI::::::::I      T:::::::::T          Y:::::::::::Y          A:::::A                 A:::::AW:::W           W:::WA:::::A                 A:::::A R::::::R     R:::::RE::::::::::::::::::::EN::::::N        N::::::NE::::::::::::::::::::ES:::::::::::::::SS S:::::::::::::::SS      B::::::::::::::::B     OO:::::::::OO         T:::::::::T      
        CCCCCCCCCCCCC    YYYYYYYYYYYYY    BBBBBBBBBBBBBBBBB   EEEEEEEEEEEEEEEEEEEEEERRRRRRRR     RRRRRRR SSSSSSSSSSSSSSS   EEEEEEEEEEEEEEEEEEEEEE       CCCCCCCCCCCCC      UUUUUUUUU      RRRRRRRR     RRRRRRRIIIIIIIIII      TTTTTTTTTTT          YYYYYYYYYYYYY         AAAAAAA                   AAAAAAAWWW             WWWAAAAAAA                   AAAAAAARRRRRRRR     RRRRRRREEEEEEEEEEEEEEEEEEEEEENNNNNNNN         NNNNNNNEEEEEEEEEEEEEEEEEEEEEE SSSSSSSSSSSSSSS    SSSSSSSSSSSSSSS        BBBBBBBBBBBBBBBBB        OOOOOOOOO           TTTTTTTTTTT      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                             tttt                                                                                             ffffffffffffffff                                                          lllllll   iiii                                                                                                                                                                                                                         
                                                                                                                                          ttt:::t                                                                                            f::::::::::::::::f                                                         l:::::l  i::::i                                                                                                                                                                                                                        
                                                                                                                                          t:::::t                                                                                           f::::::::::::::::::f                                                        l:::::l   iiii                                                                                                                                                                                                                         
                                                                                                                                          t:::::t                                                                                           f::::::fffffff:::::f                                                        l:::::l                                                                                                                                                                                                                                
                                                                                                                       ssssssssss   ttttttt:::::ttttttt      aaaaaaaaaaaaayyyyyyy           yyyyyyy         ssssssssss     aaaaaaaaaaaaa    f:::::f       ffffffeeeeeeeeeeee            ooooooooooo   nnnn  nnnnnnnn     l::::l iiiiiiinnnn  nnnnnnnn        eeeeeeeeeeee                                                                                                                                                                                      
                                                                                                                     ss::::::::::s  t:::::::::::::::::t      a::::::::::::ay:::::y         y:::::y        ss::::::::::s    a::::::::::::a   f:::::f           ee::::::::::::ee        oo:::::::::::oo n:::nn::::::::nn   l::::l i:::::in:::nn::::::::nn    ee::::::::::::ee                                                                                                                                                                                    
                                                                                                                   ss:::::::::::::s t:::::::::::::::::t      aaaaaaaaa:::::ay:::::y       y:::::y       ss:::::::::::::s   aaaaaaaaa:::::a f:::::::ffffff    e::::::eeeee:::::ee     o:::::::::::::::on::::::::::::::nn  l::::l  i::::in::::::::::::::nn  e::::::eeeee:::::ee                                                                                                                                                                                  
                                                                                                                   s::::::ssss:::::stttttt:::::::tttttt               a::::a y:::::y     y:::::y        s::::::ssss:::::s           a::::a f::::::::::::f   e::::::e     e:::::e     o:::::ooooo:::::onn:::::::::::::::n l::::l  i::::inn:::::::::::::::ne::::::e     e:::::e                                                                                                                                                                                  
                                                                                                                    s:::::s  ssssss       t:::::t              aaaaaaa:::::a  y:::::y   y:::::y          s:::::s  ssssss     aaaaaaa:::::a f::::::::::::f   e:::::::eeeee::::::e     o::::o     o::::o  n:::::nnnn:::::n l::::l  i::::i  n:::::nnnn:::::ne:::::::eeeee::::::e                                                                                                                                                                                  
                                                                                                                      s::::::s            t:::::t            aa::::::::::::a   y:::::y y:::::y             s::::::s        aa::::::::::::a f:::::::ffffff   e:::::::::::::::::e      o::::o     o::::o  n::::n    n::::n l::::l  i::::i  n::::n    n::::ne:::::::::::::::::e                                                                                                                                                                                   
                                                                                                                         s::::::s         t:::::t           a::::aaaa::::::a    y:::::y:::::y                 s::::::s    a::::aaaa::::::a  f:::::f         e::::::eeeeeeeeeee       o::::o     o::::o  n::::n    n::::n l::::l  i::::i  n::::n    n::::ne::::::eeeeeeeeeee                                                                                                                                                                                    
                                                                                                                   ssssss   s:::::s       t:::::t    tttttta::::a    a:::::a     y:::::::::y            ssssss   s:::::s a::::a    a:::::a  f:::::f         e:::::::e                o::::o     o::::o  n::::n    n::::n l::::l  i::::i  n::::n    n::::ne:::::::e                                                                                                                                                                                             
                                                                                                                   s:::::ssss::::::s      t::::::tttt:::::ta::::a    a:::::a      y:::::::y             s:::::ssss::::::sa::::a    a:::::a f:::::::f        e::::::::e               o:::::ooooo:::::o  n::::n    n::::nl::::::li::::::i n::::n    n::::ne::::::::e                                                                                                                                                                                            
                                                                                                                   s::::::::::::::s       tt::::::::::::::ta:::::aaaa::::::a       y:::::y              s::::::::::::::s a:::::aaaa::::::a f:::::::f         e::::::::eeeeeeee       o:::::::::::::::o  n::::n    n::::nl::::::li::::::i n::::n    n::::n e::::::::eeeeeeee                                                                                                                                                                                    
                                                                                                                    s:::::::::::ss          tt:::::::::::tt a::::::::::aa:::a     y:::::y                s:::::::::::ss   a::::::::::aa:::af:::::::f          ee:::::::::::::e        oo:::::::::::oo   n::::n    n::::nl::::::li::::::i n::::n    n::::n  ee:::::::::::::e                                                                                                                                                                                    
                                                                                                                     sssssssssss              ttttttttttt    aaaaaaaaaa  aaaa    y:::::y                  sssssssssss      aaaaaaaaaa  aaaafffffffff            eeeeeeeeeeeeee          ooooooooooo     nnnnnn    nnnnnnlllllllliiiiiiii nnnnnn    nnnnnn    eeeeeeeeeeeeee                                                                                                                                                                                    
                                                                                                                                                                                y:::::y                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                               y:::::y                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                              y:::::y                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                             y:::::y                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                            yyyyyyy                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
";

            Console.WriteLine(ascii);

          
        }

        // Method to simulate a typing effect
        public static void TypingEffect(string message)
        {
            foreach (char c in message)
            {
                Console.Write(c);
                Thread.Sleep(20);
            }

            Console.WriteLine();
        }
    }
}